services:
  python-greetings-app-dev:
    build: .
    image: betija/python-greetings-app:latest
    container_name: python-greetings-app-dev
    ports: 
      - 7001:3000
  python-greetings-app-stg:
    build: .
    image: betija/python-greetings-app:latest
    container_name: python-greetings-app-stg
    ports:
      - 7002:3000
  python-greetings-app-prod:
    build: .
    image: betija/python-greetings-app:latest
    container_name: python-greetings-app-prod
    ports:
      - 7003:3000